//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuciMobilv4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailPencucian
    {
        public int IdDetail { get; set; }
        public Nullable<int> IdTransaksi { get; set; }
        public Nullable<int> IdJenisPencucian { get; set; }
        public string Ukuran { get; set; }
    
        public virtual tblHarga tblHarga { get; set; }
        public virtual tblTransaksi tblTransaksi { get; set; }
    }
}
