//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuciMobilv4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHarga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHarga()
        {
            this.tblDetailPencucians = new HashSet<tblDetailPencucian>();
        }
    
        public int IdJenisPencucian { get; set; }
        public string NamaJenisPencucian { get; set; }
        public decimal kecil { get; set; }
        public decimal sedang { get; set; }
        public decimal besar { get; set; }
        public Nullable<int> gratis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetailPencucian> tblDetailPencucians { get; set; }
    }
}
