//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuciMobilv4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTransaksi()
        {
            this.tblDetailPencucians = new HashSet<tblDetailPencucian>();
        }
    
        public int IdTransaksi { get; set; }
        public int IdCustomer { get; set; }
        public string NoKendaraan { get; set; }
        public System.DateTime TanggalTransaksi { get; set; }
        public decimal TotalHarga { get; set; }
        public string StatusPembayaran { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetailPencucian> tblDetailPencucians { get; set; }
    }
}
